config/routes.rb
Rails.application.routes.draw do
  resources :orders
  resources :line_items
  resources :carts
  root :to => 'starter#home'
  
  get 'sessions/new'

  get 'users/new'

  get 'catering_items/CateringMenu'

  resources :cater_order_options

  get 'home/toppage'
  
  get 'cater_order_options/index'

  
  get    '/signup',  to: 'users#new'
  post   '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :users

  resources :products do
    get :who_bought, on: :member
  end  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :logged_in_user, only: [:toppage]
  before_action :correct_user,   only: [:user_entry]
  before_action :admin_user,     only: [:toppage]




  def toppage
    @total_orders = Order.count
  end

  def user_entry
    flash[:danger] = "Admin Access Only."
    redirect_to root_path
  end




  private
    # Use callbacks to share common setup or constraints between actions.
    def user_params
        params.require(:user).permit(:FullName, :email, :password,
                                   :PhoneNumber)
    end
    
    # Confirms a logged-in user.
    def logged_in_user
      unless logged_in?
        store_location
        flash[:danger] = "Admin Access Only."
        redirect_to login_url
        
      end
    end
    
            # Confirms the correct user.
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
      flash[:danger] = "Admin Access Only."
    end
    
    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end
    
end

app/helpers/home_helper.rb
module HomeHelper
    def admin?
  self.admin
end
end

app/views/home/toppage.html.erb
<h1>Admin Page</h1><br>

   <div class="container"  id="adminOptions">
        <div class="row">
            <div class="col-xs-12 col-sm-4">
                <div class="card">
                    <div class="card-content">
                        <h4 class="card-title">
                            View Orders
                        </h4>
                        
                        <p class="editCateringText">
                            There are <%= pluralize(@total_orders, "order") %>!
                        </p>
                        <div class="access">
                            <%= link_to 'View new orders',  orders_path, :class => "btn btn-danger" %>
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-xs-12 col-sm-4">
                <div class="card">
                    <div class="card-content">
                        <h4 class="card-title">
                            Edit Catering Order Options
                        </h4>
                        
                        <p class="editCateringText">
                            Edit, update, or delete catering options here  
                        </p>
                        <div class="access">
                            <%= link_to 'Access Catering Options', cater_order_options_path, :class => "btn btn-danger" %>
                        </div>
                    </div>
                </div>
            </div>
                    
            <div class="col-xs-12 col-sm-4">
                <div class="card">
                    <div class="card-content">
                        <h4 class="card-title">
                            View User Email List
                        </h4>
                        <p class="emailIndexText">
                            All exisiting customer emails can be found here.
                        </p>
                        <div class="access">
                            <%= link_to 'Access User List', users_path, :class => "btn btn-danger" %>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>